POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjVmMDRkYzJlODMxNGY1MmYwODE2NDE1YSIsImlhdCI6MTU5NDE2Mzg0NH0.dGpLScjghV-BqObDcZGp1DAPvJr46VXvDFGir1GcunA

{
    "title": "TEST with complete backend",
    "author": "Testguy",
    "url": "www",
    "likes": "60120"
}